spring:
  application:
    name: zuul-application

server:
  port: 8073

eureka:
   instance:
    #hostname: localhost
    prefer-ip-address: true
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://192.168.99.100:8070/eureka/

zuul:
  prefix: /api
  routes:
    main-service:
      path: /**
      serviceId: MAIN-SERVICE

