FROM java:8
EXPOSE 8081:8081
ADD build/libs/second-microservice-0.0.1-SNAPSHOT.jar second-microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "second-microservice-0.0.1-SNAPSHOT.jar"]                                                                                                                                                   #EXPOSE 8080:8080
                                                                                                                                                                  #ADD .idea/artifacts/first-microservice.jar first-microservice.jar
                                                                                                                                                                  #ENTRYPOINT ["java", "-jar", "first-microservice.jar"]