spring:
  application:
    name: main-service
server:
  port: 8072

eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8070/eureka/

#description service in */info
info:
  app:
    name: First part microservice
    description: This is my work
    version: 1.0.1