FROM java:8
EXPOSE 8083:8083
ADD build/libs/zuul-service-0.0.1-SNAPSHOT.jar zuul-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "zuul-service-0.0.1-SNAPSHOT.jar"]                                                                                                                                                   #EXPOSE 8080:8080
                                                                                                                                                                  #ADD .idea/artifacts/first-microservice.jar first-microservice.jar
                                                                                                                                                                  #ENTRYPOINT ["java", "-jar", "first-microservice.jar"]