FROM java:8
EXPOSE 8082:8082
ADD build/libs/first-microservice-0.0.1-SNAPSHOT.jar first-microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "first-microservice-0.0.1-SNAPSHOT.jar"]                                                                                                                                                   #EXPOSE 8080:8080
                                                                                                                                                                  #ADD .idea/artifacts/first-microservice.jar first-microservice.jar
                                                                                                                                                                  #ENTRYPOINT ["java", "-jar", "first-microservice.jar"]